apiVersion: v1
kind: Service
metadata:
  name: door1-sync-service
  labels:
    name: door1-sync-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: door1sync
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: door1-sync-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: door1sync
  template:
    metadata:
      labels:
        app: door1sync
    spec:
      containers:
        - name: door1sync
          args: ["1", "10"]
          image: eu.gcr.io/bk-eads-ca1/door-sync:v1