apiVersion: v1
kind: Service
metadata:
  name: door2-service
  labels:
    name: door2-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: sync
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: door2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sync
  template:
    metadata:
      labels:
        app: sync
    spec:
      containers:
        - name: door2
          args: ["2", "20"]
          image: door-sync:v1