apiVersion: v1
kind: Service
metadata:
  name: door2-sync-service
  labels:
    name: door2-sync-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: door2sync
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: door2-sync-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: door2sync
  template:
    metadata:
      labels:
        app: door2sync
    spec:
      containers:
        - name: door2sync
          args: ["2", "20"]
          image: eu.gcr.io/bk-eads-ca1/door-sync:v1